modLoader="javafml"
loaderVersion="[0,)"
license="All rights reserved"

[[mods]]
modId="avilix"
version="1.0.0"
displayName="Aivlix ECO"
authors="You"
description="Economic mod for Minecraft"

[[mods.neoforge]]
modId="avilix"

[mods.neoforge.entrypoints]
main="com.aivlix.eco.avilix"